[package]
name = 'helloextendr'
version = '0.2.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", branch = "master" }


[dev-dependencies]
extendr-engine = { path = "../../../extendr/extendr-engine/"}