# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

Source <- new.env(parent = emptyenv())

Source$new <- function(path) .Call(wrap__Source__new, path)

Source$path <- function() .Call(wrap__Source__path, self)

Source$stuffs <- function() .Call(wrap__Source__stuffs, self)

#' @export
`$.Source` <- function (self, name) { func <- Source[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Source` <- `$.Source`

